const EMAIL_EXCHANGE_TTL = 'EMAIL_EXCHANGE_TTL'
const EMAIL_EXCHANGE_DLX = 'EMAIL_EXCHANGE_DLX'

const EMAIL_QUEUE = 'EMAIL_QUEUE'
const EMAIL_QUEUE_RETRY_1 = 'EMAIL_QUEUE_RETRY_1'
const EMAIL_QUEUE_RETRY_2 = 'EMAIL_QUEUE_RETRY_2'
const EMAIL_QUEUE_RETRY_3 = 'EMAIL_QUEUE_RETRY_3'


module.exports = {
  EMAIL_EXCHANGE_TTL,
  EMAIL_EXCHANGE_DLX,
  EMAIL_QUEUE,
  EMAIL_QUEUE_RETRY_1,
  EMAIL_QUEUE_RETRY_2,
  EMAIL_QUEUE_RETRY_3
}